// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview A style recommendation AI agent.
 *
 * - recommendSimilarStyles - A function that handles the style recommendation process.
 * - StyleRecommendationInput - The input type for the recommendSimilarStyles function.
 * - StyleRecommendationOutput - The return type for the recommendSimilarStyles function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const StyleRecommendationInputSchema = z.object({
  productDescription: z.string().describe('La descripción del producto para el cual encontrar estilos similares.'),
  userPreferences: z.string().optional().describe('Preferencias opcionales del usuario para personalizar las recomendaciones.'),
});
export type StyleRecommendationInput = z.infer<typeof StyleRecommendationInputSchema>;

const StyleRecommendationOutputSchema = z.object({
  recommendations: z.array(z.string()).describe('Una lista de estilos similares o artículos complementarios.'),
});
export type StyleRecommendationOutput = z.infer<typeof StyleRecommendationOutputSchema>;

export async function recommendSimilarStyles(input: StyleRecommendationInput): Promise<StyleRecommendationOutput> {
  return recommendSimilarStylesFlow(input);
}

const prompt = ai.definePrompt({
  name: 'styleRecommendationPrompt',
  input: {schema: StyleRecommendationInputSchema},
  output: {schema: StyleRecommendationOutputSchema},
  prompt: `Eres un estilista personal que recomienda estilos similares o artículos complementarios basándose en la descripción de un producto y las preferencias del usuario.

  Descripción del Producto: {{{productDescription}}}
  Preferencias del Usuario: {{{userPreferences}}}

  Basándote en la descripción del producto y las preferencias del usuario, recomienda estilos similares o artículos complementarios. Proporciona una lista de recomendaciones.`,
});

const recommendSimilarStylesFlow = ai.defineFlow(
  {
    name: 'recommendSimilarStylesFlow',
    inputSchema: StyleRecommendationInputSchema,
    outputSchema: StyleRecommendationOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
