// This is an autogenerated file from Firebase Studio.
import { initializeApp, getApps, getApp } from 'firebase/app';
import { getFirestore } from 'firebase/firestore';

const firebaseConfig = {
  projectId: "chorus-echo",
  appId: "1:51917593184:web:42dd8f0aa42f4250a54105",
  storageBucket: "chorus-echo.firebasestorage.app",
  apiKey: process.env.NEXT_PUBLIC_FIREBASE_API_KEY,
  authDomain: "chorus-echo.firebaseapp.com",
  messagingSenderId: "51917593184"
};

// Initialize Firebase
const app = !getApps().length ? initializeApp(firebaseConfig) : getApp();
const db = getFirestore(app);

export { db };
